---
layout: post
title: "[Python] Introduction"
date: "2018-09-01"
excerpt: "Python 이란?"
output: github_document
tag: python
comments: true
categories:
  Python
---


## Python

 1990년 암스테르담 귀도 반 로섬(Guido Van Rossum) 개발한 인터프리터 언어. 인터프리터 언어는 한줄 씩 소스 코드를 해석해서 바로 실행해 결과를 확인할 수 있는 언어.
 BBC에서 방영되는 Monty pythons flying circus tv프로그램 이름을 따왔다.
 

***

### Python 설치

 Python은 `anaconda`와 같은 tool을 설치하게되면 Python이 자동으로 설치된다. <br>
 
<br>

아래 사이트에서 설치를 할 수 있다. <br>
 
[Python](https://www.python.org) <br>
[Anaconda](https://anaconda.org)

***

### Python 특징
- 문법이 아주 쉽다.
- 가독성 좋다.
- 풍부한 라이브러리 
    - `numpy`: 수학, 과학 모듈
    - `pandas`: 데이터 검색 모듈
    - `beautiple soup`: 웹스크롤링
    - `scikit-learn`: 머신러닝
- 이식성이 좋다. 
    - 쉽게 라이브러리를 추가 할 수 있다.
    - 파이썬은 C언어로 구현된 부분이여서 C계열 프로그램은 사용하기 편하다.
- Free ware
    - `FLOSS`(Free Libre and Open Source Software, 자유 오픈 소스 소프트웨어)
    - 소프트웨어의 복사본을 마음대로 배포할 수 있고 소스코드가 공개되어있어 언제든지 읽을 수 있으며 필요한 부분을 고칠 수 있고 새로운 free SW를 작성할 때 이 프로그램의 일부를 사용해도 된다는 의미.
    - `FLOSS`는 지식을 공유하는 공동체.

- 동적타이밍
    - 런타임시에 Type을 체크하는 동적타이밍을 지원
    - 메모리관리를 자동으로 해준다.

***

### 파이썬언어로 할 수 있는 일

1. 시스템 유틸리티
2. GUI 프로그램
3. C, C++ 결합
4. 웹프로그래밍(Django)
5. 수치연산프로그래밍
6. 데이터베이스 프로그래밍
7. 머신러닝, 딥러닝

***

### 파이썬의 종류

Cython(C), jython(java), Ironpython(C#), pypy(python)

