---
layout: post
title: "[Python] 파이썬에서 파일을 읽어들이기"
date: "2018-09-01"
excerpt: "파일을 불러와서 사용해보자"
output: github_document
tag:
    [python]
comments: true
categories:
  Python
---

## 파일 입출력

### 파일 Load

`open`을 사용하여 원하는 `mode`로 파일을 불러들일 수 있다. ex.`파일객체이름 = open("c:/data/test", mode)`

<br>

mode의 종류는 다음과 같다.
```
r : 읽기
w : 쓰기(파일 안에 원본 데이터는 지우고 작성된다.)
a : 추가
```
<br>

파일 사용이 끝나면 닫아준다. ex.`파일객체이름.close`

***

### Write 모드

파일 입력은 다음 예제를 통해 살펴보자. `write`모드는 기존 값은 지워지고 새로운 것으로 수정된다.

```{python}
f = open("c:/data/test.txt", "w") # 파일 객체 선언
  
for i in range(11,21): # range값 바꾸고 다시 실행해보면, 이전 값들이 없어짐
    txt = "%d 오늘하루도 행복하자\n"%i
    f.write(txt)
    
f.close() # 해줘야 저장이 됨
```

open - 실행 - close <- 이 작업을 같이 수행해야 파일이 생성된다. 

***

### Append 모드

기존의 내용은 남겨두고 새로운 데이터를 추가하는 모드이다.

```{python}
f = open('c:/data/test.txt','a') # 기존데이터에 추가

for i in range(1,11): 
    txt = "%d 오늘 하루도 행복하자\n" %i 
    f.write(txt)

f.close()
```

***

### read 모드

파일을 불러와 읽을 수 있는 모드이다.

```{python}
file = open("c:/data/test.txt","r")

data = file.readline() # 한 줄만 읽음
print(data)

data = file.readline() # 다음 한 줄 읽음
print(data)

file.close()
```

위의 코드와 print()를 반복하면 그 다음 줄을 계속 출력할 수 있다. 만약 1000줄을 출력하고 싶으면 Loop를 사용하여 1000번 실행시켜야 한다. 

***

## 관련 메소드

## csv.reader(): csv file 사용

csv file은 `csv.reader`를 사용하여 사용할 수 있다.

```{python}
import csv
file = open("C:/data/emp.csv","r")
csv.reader(file) # csv 파일 형식의 메소드로 read. 그냥 object 모양으로 주소만 저장됌
emp_csv = csv.reader(file)
emp_csv # object 정보만 보이고 그 안의 내용은 확인 불가 

next(emp_csv) # 첫 행(컬럼명)은 skip하고 다음행부터 불러들임 
for emp_list in emp_csv:
    print(emp_list)
```

참고로 `pandas` 모듈을 이용하면 보다 간편하게 구현할 수 있다.

### read(): 파일 전체를 문자열로 리턴

리스트형이 아니여서 loop로 반복할 필요가 없다.

```{python}
file = open("C:/data/test.txt","r")
data = file.read()
print(data)
file.close()
```

***

### os.path.exists(): 해당 파일이 존재하는 지

해당 파일이 존재하는 지 알고 싶을 때 쓰는 메소드이다.

```{python}
import os
os.path.exists('c:/data/test.txt') # 파일 존재여부 파악(True/False)
```

***

### readlines(): 모든 라인을 읽어 리스트에 저장

모든 라인을 읽을 수 있지만 리스트로 되어 있어서 보기 힘들다.

```{python}
file = open("C:/data/test.txt","r")
data = file.readlines()
print(data) 
file.close()
```

for문을 이용하여 하나씩 출력하는 것이 보기 편하다.

```{python}
file = open("C:/data/test.txt","r")
data = file.readlines()
for i in data:
    print(i, end = "") # 줄 사이의 공백을 없앰 
file.close()
```

참고로, `end`를 사용하지 않으면 다음과 같이 출력된다.

```{python}
file = open("C:/data/test.txt","r")
data = file.readlines()
for i in range(0,5):
    print(data[i])
file.close()
```

***

### with문: 파일객체를 자동으로 닫아주는 문

자동으로 닫아주기에 `.close()`를 사용하지 않아도 된다.

```{python}
with open("C:/data/test.txt","w") as file:
    for i in range(1,101):
        txt = "%d 오늘 하루도 행복하자 \n" %i
        print(txt, end="")
        file.write(txt)
```

리스트 변수에 담긴 text를 file로 저장하거나 읽을 수 있다.

```{python}
txt = ['Hello','World']
with open("C:/data/test_new.txt","w") as file:
    for i in txt:
        file.write(i + "\n") ## + "\n" 를 쓰지 않으면 한 줄로 write됨 

```

포멧을 사용하여 표현할 수 있다.

```{python}
txt = ['Hello','World']
with open("C:/data/test_new.txt","w") as file:
    for i in txt:
        file.write("{}\n" .format(i))
```

`read mode`는 다음과 같이 사용하면 된다.

```{python}
txt = ['Hello','World']
with open("C:/data/test_new.txt","r") as file:
    txt = file.readlines()
    for i in txt:
        print(i, end="")
```

***