---
layout: post
title: "[Python] Pandas, Numpy"
date: "2018-09-01"
excerpt: "Series와 DataFrame에 대해 알아보자"
output: github_document
tag:
    [python, series, dataframe, pandas, numpy]
comments: true
categories:
  Python
---

## pandas

- 데이터 분석 기능을 제공하는 라이브러리
- 1차원배열 : Series
- 2차원배열 : DataFrame (R에서의 Data frame과 같다) <br>


경우에 따라 다음과 같이 라이브러리를 편하게 사용할 수 있다.

```{python}
import pandas as pd # 모듈이름을 축약어로 변경
```

```{python}
from pandas import Series, DataFrame # Pandas에서 Series와 DataFrame만 사용
```


***

### Series

1차원배열로 index(색인) 배열의 데이터에 연관된 이름을 가지고 있다.

```{python}
from pandas import Series

s = Series([10,20,30,40,50])
print(s) # Series의 형태

print(s.index) # 색인 정보 확인

print(s.values) # 값 출력

s.index = ['a','b','c','d','e'] # index 수정
print(s) # index가 문자로 바뀌었다.

s2 = Series([10,20,30,40],index=['a','b','c','d']) # 생성 시 바로 인덱스 생성 가능
print(s2)


```

`Series`는 R에서 `Vector`와 같이 사칙연산이 가능하다.

```{python}
from pandas import Series

s = Series([10,20,30,40,50])

print(s+10)
print(s*10)
print(s//3)
```

#### Series에서의 인덱스 사용

`Series`의 인덱스 사용법을 익혀 알아보자

```{python}
from pandas import Series

s = Series([10,20,30,40],index=['a','b','c','d'])
print(s['a']) # 인덱스 확인

print(s[0]) # 기존에 알던대로 인덱스 사용 가능

print(s[['a','b']]) # 2개 이상일 땐 대괄호 사용

print(s[0:3]) # 0번부터 3번사이의 인덱스

print(s[-1]) # 마지막 인덱스

print(s[s>20]) # 20보다 큰 값을 찾을 때

print('a' in s) # in 연산자 사용

s['a'] = 100 # 수정
print(s) # 수정확인

s['e'] = 50 # 추가
print(s) # 추가 확인

del s['e'] # 삭제
print(s) # 삭제 확인

del s # 변수 삭제
```

중요하니 더 익혀보자

```{python}
obj = Series([10,20,30,40],index=['a','b','c','d'])

print(obj['a'])

print(obj[0])

print(obj[1:3])

print(obj['b':'d'])

print(obj[['a','c']])

print(obj[[0,2]])

print(obj[obj<30])
```

***

#### Dictionary을 Series로

Dictionary 형을 Series로 사용해보자

```{python}
from pandas import Series
dict = {'a':10,'b':20,'c':30,'d':40} # dictonary 생성

s = Series(dict)
print(s)
```

원하는 인덱스만 추출할 수 있다. `Dictionary` 데이터에서 원하는 데이터만 출력할 때 유용하다. 아래 두 코드를 비교해보면 알 수 있다.

```{python}
dict = {'a':10,'b':20,'c':30,'d':40}
ix = {'a','b','c','d'}

s1 = Series(dict, index = ix)
print(s1)
```

```{python}
import pandas as pd

dict = {'a':10,'b':20,'c':30,'d':40}
ix = {'a','b','c','z'}

s2 = Series(dict, index = ix)
print(s2)

print(pd.isnull(s2)) # NaN값 판단
print(pd.notnull(s2))
```

'z'인덱스를 들고 오려고 하였지만 'z'의 값은 존재하지 않는다. 그래서 `NaN`이 발생한다. `NaN(Not a Number)`는 인덱스 값을 찾을 수 없을 경우에 `NaN`으로 저장된다. `isnull` 혹은 `notnull` 메소드를 사용하여 Boolean값을 얻을 수 있다. <br>

간단한 예시를 살펴보자.

```{python}
dict = {'서울':100,'부산':200,'광주':300,'제주':400}
s = Series(dict)

city = ['서울','광주','제주','인천']
s = Series(dict, index = city)
print(s)

s['인천'] = 500
print(s)
```

***

### DataFrame

2차원배열로 표형식의 자료 구조이다. 각 컬럼은 서로 다른 종류의 값을 가질 수 있다.

```{python}
from pandas import DataFrame
df1 = DataFrame([[1,2,3],[4,5,6],[7,8,9]]) # 괄호 안에 괄호가 표현
print(df1)
```

`Dictionary` 데이터를 `DataFrame`으로 변환하기 편리하다.

```{python}
data = {'도시':['광주','부산','강원','인천'],
        '인구수':[100,200,50,300]}

df2 = DataFrame(data)
print(df2)

# 바로 DataFrame으로도 만들 수 있다.
df3 = DataFrame({'도시':['광주','부산','강원','인천'],
                 '인구수':[100,200,50,300]})
print(df3)
```

컬럼은 서로 다른 타입으로 `도시`와 `인구수`로 이루어져있고 index는 sequence하게 생성되었다.

***

#### DataFrame과 Series의 비교

생성하는 모습을 보고 차이를 익히자.

```{python}
s = Series([10,20,30,40],index = ['c','d','a','b'])
print(s) # Series
df = DataFrame([10,20,30,40],index = ['c','d','a','b'])
print(df) # DataFrame
```

***

#### column 다루기

`.columns`로 컬럼 정보를 확인하고 수정할 수 있다. `del`로 삭제하고 인덱싱으로 값을 추가할 수 있다.

```{python}
df = DataFrame({'도시':['광주','부산','강원','인천'],
                '인구수':[100,200,50,300]})
                
print(df.columns)

df3.columns # 컬럼 정보 확인

df3.columns = ['지역','가구수'] # 컬럼 이름 변경
print(df3)

print(df3.지역)
print(df3['지역']) # 위의 결과와 같다.
print(df3['가구수'])
print(df3['가구수']*100) # 연산작업

del df3['가구수'] # 컬럼 삭제

# Series로 결합
v = Series([1000,2000,3000,4000])

df['부채'] = v
print(df)

# 데이터 입력
df['인구수'] = [10000,20000,30000,50000]
print(df)
```

결합은 같은 인덱스 번호끼리 할 수 있다. 만약 인덱스 번호가 일치하지 않는다면 `NaN`으로 결합된다.

***

#### row 다루기

`.index`로 인덱스를 수정할 수 있고, `.ix[]`로 행 정보를 출력할 수 있다.

```{python}
df = DataFrame({'도시':['광주','부산','강원','인천'],
                '인구수':[100,200,50,300]})

df.index = ['one','two','three','four'] # 인덱스 수정
print(df)

print(df.ix['one']) # 'one'이라는 index의 행 정보
print(df.ix[0]) # 위의 결과와 같다.
```

***

#### DataFrame 다루기

컬럼이름과 인덱스 이름을 동시에 생성하는 방법과 전치하는 방법 등을 익혀보자.

```{python}
data = {'서울':{2001:200,2002:300},
        '부산':{2000:10,2001:20,2002:30}}
df = DataFrame(data)
print(df) # 인덱스 이름과 컬럼이름 동시에 생성

print(df.T) # 전치

print(df.index) # 인덱스 확인

print(df.values) # 데이터프레임에서의 값만 확인
```

#### DataFrame에서의 Data 추출

DataFrame에서 column과 row를 추출하는 방법을 다시 익혀보자

```{python}

df = DataFrame(np.arange(16).reshape(4,4),
               index=['w','x','y','z'],
               columns=['one','two','three','four'])

print(df)
print(df['one'])
print(df[['one','two']])
print(df[2:])
print(df[0:2])
print(df < 5)
print(df[df<5])
print(df[df['one']<5]) # 'one'열의 값이 5보다 작은 행만 리턴
```

***

