---
layout: post
title: "[R] Merge"
date: "2018-08-01"
excerpt: "SQL에 JOIN이 있다면 R에는 MERGE가 있다"
output: 
  html_document:
    toc: true
    toc_depth: 3
comments: true
categories: R
tag: [R, merge, join]
---

## MERGE(= JOIN)

R에서의 MERGE는 SQL에서의 JOIN과 같다. 두 데이터프레임의 공통된 값을 기준으로 병합한다. `rbind`와 `cbind`로 수행할 수 없는 경우에 사용할 수 있다.

```{r}
x <- data.frame(id = c(100,200,300),
                sql = c(70,90,80))

y <- data.frame(id = c(100,200,500),
                python = c(80,70,60))


merge(x,y)

merge(x,y, all = T) # full outer join

merge(x,y, all.x = T) # left outer join

merge(x,y, all.y = T) # right outer join
```


### 3개 이상의 data merge

3개의 데이터프레임을 `MERGE`할 시에는 다음과 같이 2개를 먼저 하고 나머지 하나를 해주면 된다.


```{r}
x <- data.frame(id = c(100,200,300),
                sql = c(70,90,80))

y <- data.frame(id = c(100,200,300),
                sql = c(80,70,60))

z <- data.frame(no = c(100,200,500),
                python = c(80,60,70))


merge(x,z) # 동일한 컬럼이 없을 경우에 Cartesian Product가 발생

merge(x,z, by.x = 'id', by.y = 'no') # 컬럼 이름을 명시해주어야 한다. (ANSI표준에서의 Join on 절)


# 3개의 데이터프레임을 조인 시
x_1 <- merge(x,z, by.x = 'id', by.y = 'no', all = T)
merge(x_1,y, by.x = 'id', by.y = 'id', all = T)
```

이제 employees와 departments 테이블을 사용하여 merge를 연습해보자

```{r}
emp <- read.csv("c:/data/emp.csv", header = T, stringsAsFactors = F)
dept <- read.csv("c:/data/dept.csv", header = T, stringsAsFactors = F)

# DEPARTMENT_ID로 MERGE
head(merge(emp,dept, by = "DEPARTMENT_ID")) # JOIN USING절

# 툭정 컬럼만 보고 싶을 시
head(merge(emp,dept, by = "DEPARTMENT_ID")[,c("LAST_NAME","DEPARTMENT_NAME")])
```

### Merge와 Grouping

Merge와 Grouping을 한꺼번에 수행하는 경우가 많다. 하지만 merge의 일양을 줄이기 위해 Grouping하고 merge하는 것이 더 효율적이다. 다음 코드를 보고 이해를해보자.

```{r}
aggregate(SALARY ~ DEPARTMENT_NAME+JOB_ID,
          merge(emp[,c("SALARY","DEPARTMENT_ID","JOB_ID")], 
                dept[,c("DEPARTMENT_ID","DEPARTMENT_NAME")], 
                by = "DEPARTMENT_ID"),
          sum)
```

위 코드보다 아래코드가 더 좋다.

```{r}
emp_temp <- aggregate(SALARY ~ DEPARTMENT_ID+JOB_ID, emp, sum)
merge(emp_temp, dept[,c("DEPARTMENT_ID","DEPARTMENT_NAME")], by = "DEPARTMENT_ID")[,c("DEPARTMENT_NAME","JOB_ID","SALARY")]
```